// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhrybutcnjdskheirbmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRocnlidXRjbmpkc2toZWlyYm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODQ0OTMsImV4cCI6MjA2NDA2MDQ5M30.Xq3mJkv-MTzxfZ7wQ9yth26ubmRXA7z56zBOL-BW3yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);